In [0]:
import numpy as np
import pandas as pd
from scipy import stats as sts
from sklearn.mixture import GaussianMixture, BayesianGaussianMixture
import warnings
warnings.filterwarnings('ignore')
from sklearn import metrics, datasets

In [0]:
# P(Y|X, P) = P(X|Y, P)P(Y) / P(X, P)
model = GaussianMixture(n_components = 3, covariance_type='full')
preds = model.fit_predict(matrix.toarray())


In [0]:
# 1 - (sum([1 for i, pred in enumerate(preds) if train_all.target[i] != pred]) / len(preds))
sum(preds == 4)

357

In [0]:
import itertools
def validate_with_mappings(preds, target, dataset):
    result = []
    combinations = []
    permutations = itertools.permutations([0, 1, 2])
    for a, b, c in permutations:
        combinations.append([a, b, c])
        mapping = {0 : a, 1: b, 2: c}
        mapped_preds = [mapping[pred] for pred in preds]
        result.append(sum([1 for i, pred in enumerate(mapped_preds) if pred != train_all.target[i]]))
    return result, combinations
        
result, combinations = validate_with_mappings(preds, train_all.target, train_all)

[1198, 1198, 1179, 1179, 1177, 1177]

In [0]:
from sklearn.datasets import fetch_20newsgroups

# train_all = fetch_20newsgroups(subset='train')
# print(train_all.target_names)

In [5]:
train_all = fetch_20newsgroups(
    subset='train', 
    categories=['comp.sys.mac.hardware', 'soc.religion.christian', 'rec.sport.hockey'])

In [0]:
print(simple_dataset.data[0])

From: erik@cheshire.oxy.edu (Erik Adams)
Subject: HELP!!  My Macintosh "luggable" has lines on its screen!
Organization: Occidental College, Los Angeles, CA 90041 USA.
Distribution: comp
Lines: 20

Okay, I don't use it very much, but I would like for it to keep working
correctly, at least as long as Apple continues to make System software
that will run on it, if slowly :-)

Here is the problem:  When the screen is tilted too far back, vertical
lines appear on the screen.  They are every 10 pixels or so, and seem
to be affected somewhat by opening windows and pulling down menus.
It looks to a semi-technical person like there is a loose connection
between the screen and the rest of the computer.

I am open to suggestions that do not involve buying a new computer,
or taking this one to the shop.  I would also like to not have
to buy one of Larry Pina's books.  I like Larry, but I'm not sure
I feel strongly enough about the computer to buy a service manual
for it.

On a related note:  what

In [0]:
simple_dataset.target

array([0, 0, 1, ..., 0, 1, 2])

In [0]:
print(simple_dataset.data[-1])

From: dlecoint@garnet.acns.fsu.edu (Darius_Lecointe)
Subject: Re: Sabbath Admissions 5of5
Organization: Florida State University
Lines: 21

I find it interesting that cls never answered any of the questions posed. 
Then he goes on the make statements which make me shudder.  He has
established a two-tiered God.  One set of rules for the Jews (his people)
and another set for the saved Gentiles (his people).  Why would God
discriminate?  Does the Jew who accepts Jesus now have to live under the
Gentile rules.

God has one set of rules for all his people.  Paul was never against the
law.  In fact he says repeatedly that faith establishes rather that annuls
the law.  Paul's point is germane to both Jews and Greeks.  The Law can
never be used as an instrument of salvation.  And please do not combine
the ceremonial and moral laws in one.

In Matt 5:14-19 Christ plainly says what He came to do and you say He was
only saying that for the Jews's benefit.  Your Christ must be a
politician, speaki

In [0]:
print(len(simple_dataset.data))

1777


In [0]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

vectorizer = CountVectorizer(max_df=500, min_df=10)
matrix = vectorizer.fit_transform(train_all.data)

In [0]:
train_all.data.shape

AttributeError: ignored

In [0]:
from sklearn.cluster.hierarchical import AgglomerativeClustering

model = AgglomerativeClustering(n_clusters=3, affinity='cosine', linkage='complete')
preds = model.fit_predict(matrix.toarray())

In [0]:
print(list(preds))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [0]:
print(matrix[0])

  (0, 877)	0.111806579628099
  (0, 880)	0.11851815596020333
  (0, 2243)	0.0925317447411647
  (0, 1136)	0.05005067187805151
  (0, 2358)	0.08407975300726757
  (0, 2820)	0.10804290934262964
  (0, 2108)	0.12357635170024023
  (0, 3035)	0.10154477899829953
  (0, 1229)	0.07360450638969387
  (0, 3262)	0.13021297950442332
  (0, 1366)	0.0836339497399446
  (0, 3305)	0.06783179408623191
  (0, 551)	0.09781400308186793
  (0, 1961)	0.22885999498507148
  (0, 619)	0.1704733433340938
  (0, 294)	0.051771062722228284
  (0, 3322)	0.09538902048354801
  (0, 2325)	0.05419206470797136
  (0, 620)	0.111806579628099
  (0, 1831)	0.1250526461821779
  (0, 3285)	0.11264581593118288
  (0, 2422)	0.09427236106959616
  (0, 301)	0.05563256696046784
  (0, 855)	0.20162554088271675
  (0, 2868)	0.08596208970791507
  :	:
  (0, 900)	0.12357635170024023
  (0, 354)	0.06947437383545056
  (0, 2048)	0.07488448956033757
  (0, 1991)	0.07113027685860011
  (0, 926)	0.11742059318548874
  (0, 3722)	0.09501028877632493
  (0, 1905)	0.081735

In [0]:
vectorizer.get_feature_names()

['00',
 '000',
 '01',
 '02',
 '03',
 '030',
 '0358',
 '04',
 '040',
 '05',
 '06',
 '07',
 '08',
 '09',
 '10',
 '100',
 '1000',
 '101',
 '102',
 '104',
 '105',
 '106',
 '109',
 '11',
 '110',
 '112',
 '113',
 '119',
 '12',
 '120',
 '126',
 '127',
 '128',
 '129',
 '13',
 '132',
 '133',
 '14',
 '140',
 '15',
 '150',
 '152',
 '16',
 '160',
 '17',
 '170',
 '175',
 '18',
 '180',
 '19',
 '1987',
 '1988',
 '1989',
 '199',
 '1990',
 '1991',
 '1992',
 '1993',
 '1993apr14',
 '1993apr15',
 '1993apr16',
 '1993apr18',
 '1993apr19',
 '1993apr20',
 '1993apr5',
 '1993apr6',
 '1d17',
 '1d20',
 '1st',
 '20',
 '200',
 '2000',
 '203',
 '21',
 '210',
 '22',
 '23',
 '230',
 '24',
 '240',
 '241',
 '25',
 '253',
 '256',
 '25mhz',
 '26',
 '27',
 '28',
 '286',
 '29',
 '2nd',
 '30',
 '300',
 '30602',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '386',
 '39',
 '3rd',
 '40',
 '400',
 '403',
 '408',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '486',
 '49',
 '4mb',
 '4th',
 '50',
 '500',
 '51'

In [24]:
from sklearn.cluster import KMeans

model = KMeans(n_clusters=3, random_state=1)
preds = model.fit_predict(matrix.toarray())
print(preds)

[0 0 0 ... 0 0 0]


In [0]:
print(simple_dataset.target)

[0 0 1 ... 0 1 2]


In [0]:
mapping = {2 : 1, 1: 2, 0: 0}
mapped_preds = [mapping[pred] for pred in preds]
print(float(sum(mapped_preds != simple_dataset.target)) / len(simple_dataset.target))

0.979741136747327


In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
clf = LogisticRegression()
# print (cross_val_score(clf, matrix, simple_dataset.target).mean())

In [0]:
dataset = fetch_20newsgroups(
    subset='train', 
    categories=['comp.sys.mac.hardware', 'comp.os.ms-windows.misc', 'comp.graphics'])
dataset

{'DESCR': '.. _20newsgroups_dataset:\n\nThe 20 newsgroups text dataset\n------------------------------\n\nThe 20 newsgroups dataset comprises around 18000 newsgroups posts on\n20 topics split in two subsets: one for training (or development)\nand the other one for testing (or for performance evaluation). The split\nbetween the train and test set is based upon a messages posted before\nand after a specific date.\n\nThis module contains two loaders. The first one,\n:func:`sklearn.datasets.fetch_20newsgroups`,\nreturns a list of the raw texts that can be fed to text feature\nextractors such as :class:`sklearn.feature_extraction.text.CountVectorizer`\nwith custom parameters so as to extract feature vectors.\nThe second one, :func:`sklearn.datasets.fetch_20newsgroups_vectorized`,\nreturns ready-to-use features, i.e., it is not necessary to use a feature\nextractor.\n\n**Data Set Characteristics:**\n\n    =================   ==========\n    Classes                     20\n    Samples total  

In [0]:
matrix = vectorizer.fit_transform(dataset.data)
model = KMeans(n_clusters=3, random_state=42)
preds = model.fit_predict(matrix.toarray())
print(preds)
print(dataset.target)

[2 1 0 ... 2 0 2]
[2 1 1 ... 2 0 2]


0.713063320022818


In [0]:
clf = LogisticRegression()
print(cross_val_score(clf, matrix, dataset.target).mean())

0.9264143264143264


In [26]:
from sklearn.decomposition import TruncatedSVD

model = KMeans(n_clusters=3, random_state=42)
svd = TruncatedSVD(n_components=1000, random_state=123)
features = svd.fit_transform(matrix)
preds = model.fit_predict(features)
print(preds)
print(train_all.target)

[0 0 0 ... 0 0 0]
[0 0 1 ... 0 1 2]


In [28]:
import itertools
def validate_with_mappings(preds, target, dataset):
    permutations = itertools.permutations([0, 1, 2])
    for a, b, c in permutations:
        mapping = {2 : a, 1: b, 0: c}
        mapped_preds = [mapping[pred] for pred in preds]
        print(float(sum(mapped_preds != target)) / len(target))
        
validate_with_mappings(preds, train_all.target, train_all)

0.6623522791221159
0.6634777715250422
0.6623522791221159
0.6741699493528419
0.6634777715250422
0.6741699493528419


In [31]:
model = KMeans(n_clusters=3, random_state=42)
svd = TruncatedSVD(n_components=200, random_state=321)
features = svd.fit_transform(matrix)
preds = model.fit_predict(features)
print(preds)
print(train_all.target)
validate_with_mappings(preds, train_all.target, train_all)

[0 0 0 ... 0 0 0]
[0 0 1 ... 0 1 2]
0.6623522791221159
0.6634777715250422
0.6623522791221159
0.6741699493528419
0.6634777715250422
0.6741699493528419


In [32]:
import sklearn
iris = sklearn.datasets.load_iris()
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [0]:
X = iris.data
y = iris.target

In [34]:
model = KMeans(n_clusters=4, random_state=42)
preds = model.fit_predict(X)
print(preds)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 3 3 3 2 3 2 3 2 3 2 2 2 2 3 2 3 2 2 3 2 3 2 3 3
 3 3 3 3 3 2 2 2 2 3 2 3 3 3 2 2 2 3 2 2 2 2 2 3 2 2 1 3 1 1 1 1 2 1 1 1 3
 3 1 3 3 1 1 1 1 3 1 3 1 3 1 1 3 3 1 1 1 1 1 3 3 1 1 1 3 1 1 1 3 1 1 1 3 3
 1 3]


In [35]:
import itertools
from sklearn import metrics
def validate_with_mappings(preds, target, dataset):
    permutations = itertools.permutations([0, 1, 2, 3])
    for a, b, c, d in permutations:
        mapping = {2 : a, 1: b, 0: c, 3: d}
        mapped_preds = [mapping[pred] for pred in preds]
        print(float(sum(mapped_preds != target)) / len(target))
        # print(metrics.accuracy_score(target, mapped_preds))
        

validate_with_mappings(preds, y, iris)

1.0
0.8866666666666667
0.7866666666666666
0.6333333333333333
0.8866666666666667
0.8466666666666667
0.82
0.7066666666666667
0.2733333333333333
0.6066666666666667
0.37333333333333335
0.82
0.9933333333333333
0.84
0.66
0.9933333333333333
0.5066666666666667
0.9933333333333333
0.8866666666666667
0.8466666666666667
0.5533333333333333
1.0
0.3
0.7866666666666666


In [0]:
from sklearn.cluster import DBSCAN

In [44]:
model = DBSCAN(eps=0.5, min_samples=3)
preds = model.fit_predict(X)
print(preds)
# preds = [i+1 for i in preds]
# validate_with_mappings(preds, y, iris)

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0
  0  0  1  1  1  1  1  1  1  2  1  1  2  1  1  1  1  1  1  1 -1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  2  1  1
  1  1  2  1  1  1  1  1  1  3 -1  1 -1 -1  1  1  1  1  1  1  1 -1  3  1
  1  1  3  1  1  1  1  1  1  1  1 -1  1  1 -1 -1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1]
