In [0]:
from sklearn import model_selection, datasets

import numpy as np

In [0]:
# X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.3)

In [0]:
X = range(0,10)

In [5]:
kf = model_selection.KFold(n_splits = 5)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)


[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [6]:
kf = model_selection.KFold(n_splits = 5, shuffle = True)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[1 2 4 5 6 7 8 9] [0 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 3 4 5 7 8 9] [2 6]
[0 2 3 4 5 6 7 8] [1 9]
[0 1 2 3 4 5 6 9] [7 8]


In [10]:
y = np.array([0] * 5 + [1] * 5)
print(y)
# [0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
skf = model_selection.StratifiedKFold(n_splits = 2, shuffle = True)
for train_indices, test_indices in skf.split(X, y):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[1 4 5 8 9] [0 2 3 6 7]
[0 2 3 6 7] [1 4 5 8 9]


In [12]:
target = np.array([0, 1] * 5)
print(target)

skf = model_selection.StratifiedKFold(n_splits = 5,shuffle = True)
for train_indices, test_indices in skf.split(X, target):
    print(train_indices, test_indices)

[0 1 0 1 0 1 0 1 0 1]
[1 2 3 4 6 7 8 9] [0 5]
[0 2 3 4 5 7 8 9] [1 6]
[0 1 2 3 4 5 6 9] [7 8]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 5 6 7 8] [4 9]


In [14]:
ss = model_selection.ShuffleSplit(n_splits = 20, test_size = 0.2)

for train_indices, test_indices in ss.split(X):
    print(train_indices, test_indices)

[4 6 2 1 0 5 7 9] [8 3]
[3 2 7 4 0 6 9 5] [8 1]
[9 3 0 8 4 1 5 6] [2 7]
[5 9 3 1 7 6 0 4] [2 8]
[3 1 2 5 0 6 4 7] [9 8]
[8 9 5 2 0 7 1 3] [6 4]
[2 4 5 7 9 0 8 3] [6 1]
[3 2 0 9 4 8 6 1] [5 7]
[3 5 4 0 8 2 9 6] [1 7]
[8 0 6 9 3 7 1 5] [2 4]
[3 1 9 0 4 5 8 7] [2 6]
[6 1 2 9 0 7 5 8] [4 3]
[9 5 1 6 7 2 8 0] [3 4]
[4 9 5 8 0 1 6 2] [3 7]
[0 1 3 4 9 6 2 5] [8 7]
[1 6 8 9 0 4 7 3] [2 5]
[8 1 3 9 5 0 2 7] [4 6]
[8 7 4 9 0 3 6 2] [1 5]
[3 0 4 7 2 1 6 8] [5 9]
[9 8 4 1 7 3 0 5] [6 2]


In [18]:
target = np.array([0] * 5 + [1] * 5)
print(target)

sss = model_selection.StratifiedShuffleSplit(n_splits = 4, test_size = 0.2)
for train_indices, test_indices in sss.split(X, target):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[1 2 6 3 8 9 7 0] [5 4]
[1 0 8 3 4 9 5 6] [2 7]
[3 8 1 6 9 2 7 4] [5 0]
[3 8 6 5 2 4 1 7] [0 9]


In [19]:
loo = model_selection.LeaveOneOut()

for train_indices, test_index in loo.split(X):
    print(train_indices, test_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [0]:
from sklearn import model_selection, datasets, linear_model, metrics

import numpy as np
import pandas as pd

In [0]:
iris = datasets.load_iris()
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.25)



In [23]:
classifier = linear_model.SGDClassifier()
classifier.get_params().keys()

dict_keys(['alpha', 'average', 'class_weight', 'early_stopping', 'epsilon', 'eta0', 'fit_intercept', 'l1_ratio', 'learning_rate', 'loss', 'max_iter', 'n_iter_no_change', 'n_jobs', 'penalty', 'power_t', 'random_state', 'shuffle', 'tol', 'validation_fraction', 'verbose', 'warm_start'])

In [0]:
parameters_grid = {
    'loss' : ['hinge', 'log', 'squared_loss'],
    'penalty' : ['l1', 'l2'],
    'max_iter' : np.arange(1, 10),
    'alpha' : np.linspace(0.0001, 0.001, 5),
}

In [0]:
cv1 = model_selection.StratifiedKFold(n_splits=10)
cv2= model_selection.StratifiedShuffleSplit(n_splits=10, test_size=0.25)

In [0]:
grid_cv = model_selection.GridSearchCV(classifier, parameters_grid, scoring = 'accuracy', cv = cv1)

In [45]:
%%time
grid_cv.fit(train_data, train_labels)

Streaming output truncated to the last 5000 lines.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  Con

CPU times: user 8.92 s, sys: 526 ms, total: 9.45 s
Wall time: 8.77 s


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_mo

GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=None, shuffle=False),
             error_score=nan,
             estimator=SGDClassifier(alpha=0.0001, average=False,
                                     class_weight=None, early_stopping=False,
                                     epsilon=0.1, eta0=0.0, fit_intercept=True,
                                     l1_ratio=0.15, learning_rate='optimal',
                                     loss='hinge', max_iter=1000,
                                     n_iter_no_change=5, n_jobs=None,
                                     penalty='l2', power_t=0.5,
                                     random...ue, tol=0.001,
                                     validation_fraction=0.1, verbose=0,
                                     warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': array([0.0001  , 0.000325, 0.00055 , 0.000775, 0.001   ]),
                         'loss': ['hinge', 'log', 'squared_los

In [31]:

metrics.accuracy_score(grid_cv.best_estimator_.predict(test_data), test_labels)

0.9210526315789473

In [46]:
print(grid_cv.best_score_)
print(grid_cv.best_params_)


0.918939393939394
{'alpha': 0.0007750000000000001, 'loss': 'hinge', 'max_iter': 8, 'penalty': 'l1'}


In [0]:
randomized_grid_cv = model_selection.RandomizedSearchCV(classifier, parameters_grid, scoring = 'accuracy', cv = cv, n_iter = 20, 
                                                   random_state = 0)

In [48]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_mo

CPU times: user 636 ms, sys: 32.9 ms, total: 669 ms
Wall time: 622 ms


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_mo

RandomizedSearchCV(cv=StratifiedKFold(n_splits=10, random_state=None, shuffle=False),
                   error_score=nan,
                   estimator=SGDClassifier(alpha=0.0001, average=False,
                                           class_weight=None,
                                           early_stopping=False, epsilon=0.1,
                                           eta0=0.0, fit_intercept=True,
                                           l1_ratio=0.15,
                                           learning_rate='optimal',
                                           loss='hinge', max_iter=1000,
                                           n_iter_no_change=5, n_jobs=None,
                                           penalty='l2', power_t=0.5,...
                                           tol=0.001, validation_fraction=0.1,
                                           verbose=0, warm_start=False),
                   iid='deprecated', n_iter=20, n_jobs=None,
                   param_distribu

In [49]:
print(randomized_grid_cv.best_score_)
print(randomized_grid_cv.best_params_)

0.8121212121212121
{'penalty': 'l1', 'max_iter': 6, 'loss': 'log', 'alpha': 0.001}
